# Generated by Django 2.2.7 on 2021-06-22 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210622_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
