# Generated by Django 2.2.7 on 2021-06-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_task_user'),
        ('todo', '0005_auto_20210622_0849'),
    ]

    operations = [
    ]
