# Generated by Django 2.2.7 on 2021-06-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_merge_20210623_1020'),
        ('todo', '0007_auto_20210624_1643'),
    ]

    operations = [
    ]
