# Generated by Django 2.2.7 on 2021-07-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20210624_1118'),
        ('todo', '0009_task_is_active'),
    ]

    operations = [
    ]
