# Generated by Django 3.2.4 on 2021-06-15 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_idea_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Idea',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
