# Generated by Django 2.2.7 on 2021-07-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20210704_2044'),
        ('project', '0012_auto_20210624_1118'),
    ]

    operations = [
    ]
