# Generated by Django 3.1.4 on 2021-07-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('imdb_id', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=500)),
                ('rank', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
