# Generated by Django 3.1.4 on 2021-07-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_usermovie_usertvshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_url',
            field=models.URLField(default='none', max_length=500),
            preserve_default=False,
        ),
    ]
